blueprint:
  name: Door open TTS announcer with climate+temp status check & initial delay
  domain: automation
  input:
    door_entity:
      name: Door Sensor
      description: Entity to trigger announcement
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    climate_entity:
      name: Thermostat Entity
      description: The ecobee thermostat entity
      selector:
        entity:
          domain: climate
    weather_entity:
      name: Weather Entity
      description: The source of outside temperature
      selector:
        entity:
          domain: weather
    minimum_temperature:
      name: Minimum Temperature
      description: Min temp
      default: 68
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: degrees
    maximum_temperature:
      name: Maximum Temperature
      description: Max temp
      default: 78
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: degrees
    speaker_target:
      name: Speaker
      description: Entity to announce event on (choose an Entity, not a Device!)
      selector:
        target:
          entity:
            domain: media_player
    announcement_message:
      name: Announcement message
      description: What to say when door is left open
      default: The door has been left open
    initial_delay:
      name: Initial delay
      description: Time before first announcement
      selector:
        duration:
          enable_day: false
      default:
        hours: 0
        minutes: 0
        seconds: 60
    cooldown:
      name: Announcement repetition frequency
      description: Time between repeated announcements
      default: 30
      selector:
        number:
          min: 15
          max: 600
          unit_of_measurement: seconds

mode: single

trigger:
  platform: state
  entity_id: !input door_entity
  from: "off"
  to: "on"
  for: !input initial_delay 

condition:
  alias: "Heat pump on or temp outside range"
  or:
    - condition: state
      entity_id: !input climate_entity
      attribute: fan
      state: 'on'
    - condition: numeric_state
      entity_id: !input weather_entity
      attribute: temperature
      below: !input minimum_temperature
    - condition: numeric_state
      entity_id: !input weather_entity
      attribute: temperature
      above: !input maximum_temperature
      

action:
  - alias: Repeat the sequence UNTIL the door is closed
    repeat:
      sequence:
        - condition: state
          entity_id: !input door_entity
          state: 'on'
        - service: tts.google_translate_say
          target: !input speaker_target
          data:
            message: !input announcement_message
        - delay: !input cooldown 
      until:
        - condition: state
          entity_id: !input door_entity
          state: 'off'
