blueprint:
  name: Door open TTS announcer with initial delay v3
  domain: automation
  input:
    door_entity:
      name: Door Sensor
      description: Entity to trigger announcement
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    speaker_target:
      name: Speaker
      description: Entity to announce event on (choose an Entity, not a Device!)
      selector:
        target:
          entity:
            domain: media_player
    announcement_message:
      name: Announcement message
      description: What to say when door is left open
    initial_delay:
      name: Initial delay
      description: Time before first announcement
      default: 00:00:60
      selector:
        duration:
          enable_day: false
    cooldown:
      name: Announcement repetition frequency
      description: Time between repeated announcements
      default: 10
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

mode: single

trigger:
  platform: state
  entity_id: !input door_entity
  from: "off"
  to: "on"
  for: !input initial_delay 

action:
  - alias: Repeat the sequence UNTIL the door is closed
    repeat:
      sequence:
        - condition: state
          entity_id: !input door_entity
          state: 'on'
        - service: tts.google_translate_say
          target: !input speaker_target
          data:
            message: !input announcement_message
        - delay: !input cooldown 
      until:
        - condition: state
          entity_id: !input door_entity
          state: 'off'
