blueprint:
  name: Door open TTS announcer with initial delay
  domain: automation
  input:
    door_entity:
      name: Door Sensor
      description: Entity to trigger announcement
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    speaker_target:
      name: Speaker
      description: Entity to announce event on (choose an Entity, not a Device!)
      selector:
        target:
          entity:
            domain: media_player
    announcement_message:
      name: Announcement message
      description: What to say when door is left open
      default: The door has been left open
    initial_delay:
      name: Initial delay
      description: Time before first announcement
      selector:
        duration:
          enable_day: false
      default:
        hours: 0
        minutes: 0
        seconds: 60
    cooldown:
      name: Announcement repetition frequency
      description: Time between repeated announcements
      default: 30
      selector:
        number:
          min: 15
          max: 600
          unit_of_measurement: seconds

mode: single

trigger:
  platform: state
  entity_id: !input door_entity
  from: "off"
  to: "on"
  for: !input initial_delay 

action:
  - alias: Repeat the sequence UNTIL the door is closed
    repeat:
      sequence:
        - condition: state
          entity_id: !input door_entity
          state: 'on'
        - service: tts.speak
          target: tts.google_en_com # TODO perhaps makes this configurable
          data:
            media_player_entity_id: !input speaker_target
            message: !input announcement_message
        - delay: !input cooldown 
      until:
        - condition: state
          entity_id: !input door_entity
          state: 'off'
